"""Tests for the RSS scraper.

These guard against regressions on the 403-Forbidden fix:

- Every RSS request must ship a realistic browser User-Agent (generated by
  `fake-useragent`) and RSS-friendly Accept headers.
- Transient 5xx / 429 responses must be retried; 4xx responses like 403
  must be logged and skipped.
- URLs with unresolved `${VAR}` placeholders must be skipped with a
  clear warning instead of hitting the network.
"""

from __future__ import annotations

import asyncio
from datetime import datetime, timedelta, timezone

import httpx
import pytest

from src.models import RSSSourceConfig
from src.scrapers import rss as rss_module
from src.scrapers.rss import (
    _FALLBACK_USER_AGENT,
    RSSScraper,
    build_rss_headers,
)


SAMPLE_FEED = """<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <title>Sample</title>
    <link>https://example.com</link>
    <description>Sample feed</description>
    <item>
      <title>Hello world</title>
      <link>https://example.com/hello</link>
      <guid>https://example.com/hello</guid>
      <pubDate>{pub_date}</pubDate>
      <description>Body</description>
    </item>
  </channel>
</rss>
"""


def _recent_pubdate() -> str:
    # RFC 822 pubDate, 1 hour ago, so it falls within the `since` window.
    dt = datetime.now(timezone.utc) - timedelta(hours=1)
    return dt.strftime("%a, %d %b %Y %H:%M:%S +0000")


def _make_scraper(handler: httpx.MockTransport):
    client = httpx.AsyncClient(transport=handler, timeout=5.0)
    source = RSSSourceConfig(
        name="Example",
        url="https://example.com/feed",
        enabled=True,
    )
    return RSSScraper([source], client), client


def _looks_like_browser_ua(ua: str) -> bool:
    """True if the UA string looks like a mainstream desktop browser."""
    if not ua or "python-httpx" in ua.lower() or "httpx" in ua.lower():
        return False
    # Every modern browser UA starts with "Mozilla/5.0".
    if not ua.startswith("Mozilla/5.0"):
        return False
    return any(token in ua for token in ("Chrome/", "Firefox/", "Safari/", "Edg/"))


def test_rss_sends_browser_user_agent_and_accept_headers():
    captured: dict[str, httpx.Headers] = {}

    def handler(request: httpx.Request) -> httpx.Response:
        captured["headers"] = request.headers
        return httpx.Response(
            200,
            text=SAMPLE_FEED.format(pub_date=_recent_pubdate()),
            headers={"content-type": "application/rss+xml"},
        )

    scraper, client = _make_scraper(httpx.MockTransport(handler))
    try:
        since = datetime.now(timezone.utc) - timedelta(hours=24)
        items = asyncio.run(scraper.fetch(since))
    finally:
        asyncio.run(client.aclose())

    assert len(items) == 1
    assert items[0].title == "Hello world"

    headers = captured["headers"]
    assert _looks_like_browser_ua(headers["user-agent"]), (
        f"UA is not browser-like: {headers['user-agent']}"
    )
    # Must advertise RSS / Atom / XML so strict servers don't 406/403 us.
    assert "application/rss+xml" in headers["accept"]
    assert "application/atom+xml" in headers["accept"]
    assert headers["accept-language"].startswith("en")


def test_build_rss_headers_rotates_user_agent():
    """build_rss_headers() must draw a fresh UA each call.

    fake-useragent can occasionally repeat by chance, so we sample enough
    times that a collision on every sample is statistically impossible.
    """
    seen = {build_rss_headers()["User-Agent"] for _ in range(30)}
    # At minimum the UAs must be browser-like strings.
    assert all(_looks_like_browser_ua(ua) for ua in seen), seen
    # In practice with 30 samples across Chrome/Firefox/Safari/Edge we
    # should see multiple distinct values unless fake-useragent is absent.
    if rss_module._UA_GENERATOR is not None:
        assert len(seen) > 1, (
            "Expected fake-useragent to rotate UA across requests, "
            f"but only saw: {seen}"
        )


def test_build_rss_headers_falls_back_when_generator_unavailable(monkeypatch):
    monkeypatch.setattr(rss_module, "_UA_GENERATOR", None)
    headers = build_rss_headers()
    assert headers["User-Agent"] == _FALLBACK_USER_AGENT
    assert "application/rss+xml" in headers["Accept"]


def test_build_rss_headers_falls_back_when_generator_raises(monkeypatch):
    class _BrokenUA:
        @property
        def random(self):
            raise RuntimeError("boom")

    monkeypatch.setattr(rss_module, "_UA_GENERATOR", _BrokenUA())
    headers = build_rss_headers()
    assert headers["User-Agent"] == _FALLBACK_USER_AGENT


def test_rss_retries_on_transient_5xx_then_succeeds(monkeypatch):
    monkeypatch.setattr(rss_module, "_BASE_BACKOFF", 0)

    call_count = {"n": 0}
    seen_uas: list[str] = []

    def handler(request: httpx.Request) -> httpx.Response:
        call_count["n"] += 1
        seen_uas.append(request.headers["user-agent"])
        if call_count["n"] < 3:
            return httpx.Response(503, text="busy")
        return httpx.Response(
            200,
            text=SAMPLE_FEED.format(pub_date=_recent_pubdate()),
            headers={"content-type": "application/rss+xml"},
        )

    scraper, client = _make_scraper(httpx.MockTransport(handler))
    try:
        since = datetime.now(timezone.utc) - timedelta(hours=24)
        items = asyncio.run(scraper.fetch(since))
    finally:
        asyncio.run(client.aclose())

    assert call_count["n"] == 3
    assert len(items) == 1
    # Each retry should use a freshly-generated UA (all browser-like).
    assert all(_looks_like_browser_ua(ua) for ua in seen_uas), seen_uas


def test_rss_gives_up_after_max_attempts_on_403(monkeypatch, caplog):
    monkeypatch.setattr(rss_module, "_BASE_BACKOFF", 0)

    call_count = {"n": 0}

    def handler(request: httpx.Request) -> httpx.Response:
        call_count["n"] += 1
        return httpx.Response(403, text="forbidden")

    scraper, client = _make_scraper(httpx.MockTransport(handler))
    try:
        since = datetime.now(timezone.utc) - timedelta(hours=24)
        with caplog.at_level("WARNING"):
            items = asyncio.run(scraper.fetch(since))
    finally:
        asyncio.run(client.aclose())

    # 403 is not in the retryable set, so exactly one request.
    assert call_count["n"] == 1
    assert items == []
    assert any("HTTP 403" in rec.message for rec in caplog.records)


def test_rss_skips_feed_with_unresolved_env_var(monkeypatch, caplog):
    monkeypatch.delenv("HORIZON_TEST_MISSING_KEY", raising=False)

    def handler(request: httpx.Request) -> httpx.Response:
        raise AssertionError("HTTP request should not be made for unresolved env var")

    client = httpx.AsyncClient(transport=httpx.MockTransport(handler), timeout=5.0)
    source = RSSSourceConfig(
        name="Needs-Key",
        url="https://example.com/feed?key=${HORIZON_TEST_MISSING_KEY}",
        enabled=True,
    )
    scraper = RSSScraper([source], client)
    try:
        since = datetime.now(timezone.utc) - timedelta(hours=24)
        with caplog.at_level("WARNING"):
            items = asyncio.run(scraper.fetch(since))
    finally:
        asyncio.run(client.aclose())

    assert items == []
    assert any(
        "HORIZON_TEST_MISSING_KEY" in rec.message for rec in caplog.records
    ), "expected a warning about the missing env var"
