"""Tag alias lookup for multilingual matching in setup wizard.

Mirrors horizon-site/app/lib/tagAliases.ts — canonical tag -> aliases
(including Chinese, Vietnamese, abbreviations, and common variations).
"""

TAG_ALIASES: dict[str, list[str]] = {
    "ads": ["广告", "advertising", "quảng cáo", "ads"],
    "adsense": ["AdSense", "Google AdSense", "谷歌广告联盟", "quảng cáo Google"],
    "affiliate": ["联盟营销", "affiliate-marketing", "affiliate marketing", "tiếp thị liên kết", "kiếm tiền affiliate"],
    "ai": ["人工智能", "AI", "artificial-intelligence"],
    "aigc": ["生成式AI", "生成式人工智能", "generative-ai"],
    "airdrop": ["空投", "airdrop", "săn airdrop"],
    "algorithms": ["算法", "Algorithms"],
    "analysis": ["分析", "Analysis"],
    "analytics": ["数据分析", "Analytics"],
    "android": ["Android", "安卓"],
    "angular": ["Angular"],
    "arbitrage": ["套利", "arbitrage", "kinh doanh chênh lệch giá", "chênh lệch giá"],
    "automation": ["自动化", "automation", "tự động hóa"],
    "aws": ["AWS", "Amazon Web Services", "亚马逊云"],
    "azure": ["Azure", "微软云"],
    "backend": ["后端", "Backend"],
    "bigdata": ["大数据", "big-data", "Big Data"],
    "blackhat": ["黑帽", "black-hat", "black hat", "blackhat", "mũ đen", "kỹ thuật mũ đen"],
    "blockchain": ["区块链", "Blockchain", "Web3"],
    "bot": ["机器人", "bot", "bot tự động"],
    "c": ["C语言", "C"],
    "carding": ["盗刷", "carding"],
    "chinese": ["中文", "Chinese"],
    "cicd": ["CI/CD", "持续集成", "持续部署"],
    "cli": ["命令行", "CLI", "command-line"],
    "copywriting": ["文案", "copywriting", "viết quảng cáo", "viết content"],
    "cpa": ["CPA", "cost-per-action", "每次行动成本", "chi phí mỗi hành động"],
    "cpp": ["C++", "c++"],
    "cracking": ["破解", "cracking", "cracked", "bẻ khóa"],
    "crypto-earning": ["加密货币赚钱", "crypto earning", "crypto-earning", "kiếm tiền crypto", "kiếm tiền tiền số"],
    "cryptography": ["密码学", "加密"],
    "css": ["CSS", "样式"],
    "cv": ["计算机视觉", "CV", "computer-vision"],
    "dataeng": ["数据工程", "data-engineering", "Data Engineering"],
    "datascience": ["数据科学", "data-science", "Data Science"],
    "datastructure": ["数据结构", "data-structures", "Data Structures"],
    "defi": ["DeFi", "去中心化金融"],
    "designpattern": ["设计模式", "design-patterns", "Design Patterns"],
    "devops": ["DevOps"],
    "distributed": ["分布式系统", "distributed-systems"],
    "django": ["Django"],
    "dl": ["深度学习", "deep-learning", "神经网络"],
    "docker": ["Docker", "docker", "容器"],
    "dropservicing": ["服务转售", "drop-servicing", "drop servicing", "bán lại dịch vụ"],
    "dropshipping": ["一件代发", "dropshipping", "drop shipping", "bán hàng dropshipping"],
    "ecommerce": ["电商", "电子商务", "e-commerce", "ecommerce", "thương mại điện tử"],
    "editor": ["编辑器", "Editor"],
    "email-marketing": ["邮件营销", "email-marketing", "email marketing", "tiếp thị email", "EDM"],
    "embedded": ["嵌入式", "Embedded"],
    "embodied": ["具身智能", "Embodied Intelligence"],
    "es": ["Elasticsearch", "elasticsearch", "搜索引擎"],
    "ethereum": ["以太坊", "Ethereum"],
    "flutter": ["Flutter"],
    "forex": ["外汇", "forex", "FX", "ngoại hối"],
    "freelance": ["自由职业", "freelance", "freelancing", "làm tự do", "làm freelance"],
    "frontend": ["前端", "Frontend"],
    "gcp": ["GCP", "Google Cloud", "谷歌云"],
    "giveaway": ["福利", "免费送", "giveaway", "free", "tặng miễn phí", "tặng quà"],
    "golang": ["Go", "Golang", "go语言"],
    "growth": ["增长", "增长黑客", "growth", "growth-hacking", "growth hacking", "tăng trưởng", "hack tăng trưởng"],
    "hardware": ["硬件", "Hardware"],
    "html": ["HTML"],
    "indiehacker": ["独立开发者", "indie-hacker", "indie hacker", "indie hackers", "indiehackers", "lập trình viên độc lập"],
    "ios": ["iOS", "苹果开发"],
    "java": ["Java", "java语言"],
    "javascript": ["JavaScript", "JS", "js", "ECMAScript"],
    "k8s": ["Kubernetes", "kubernetes", "容器编排"],
    "kernel": ["内核", "Kernel"],
    "kotlin": ["Kotlin"],
    "linux": ["Linux", "linux"],
    "llm": ["大语言模型", "LLM", "large-language-model", "大模型"],
    "llm-inference": ["大模型推理", "LLM Inference", "llm-inference", "推理"],
    "maker": [],
    "marketing": ["营销", "marketing", "tiếp thị"],
    "method": ["方法", "method", "phương pháp", "thủ thuật"],
    "microservice": ["微服务", "microservices", "Microservices"],
    "ml": ["机器学习", "machine-learning"],
    "mmo": ["网赚", "赚钱", "make-money-online", "make money online", "MMO", "kiếm tiền online", "kiếm tiền mạng"],
    "monetization": ["变现", "货币化", "monetization", "monetize", "kiếm tiền", "thương mại hóa"],
    "mongo": ["MongoDB", "mongodb"],
    "mysql": ["MySQL", "mysql"],
    "neovim": ["Neovim", "neovim"],
    "news": ["新闻"],
    "nextjs": ["Next.js", "NextJS"],
    "nft": ["NFT", "非同质化代币"],
    "niche": ["利基", "细分市场", "niche", "ngách", "thị trường ngách"],
    "nlp": ["自然语言处理", "NLP", "natural-language-processing"],
    "nodejs": ["Node.js", "NodeJS", "node"],
    "os": ["操作系统", "operating-system"],
    "passive-income": ["被动收入", "passive-income", "passive income", "thu nhập thụ động"],
    "performance": ["性能优化", "Performance"],
    "php": ["PHP", "php语言"],
    "pl": ["编程语言", "programming-languages", "Programming Languages", "语言"],
    "postgres": ["PostgreSQL", "Postgres", "PG", "pg", "postgresql"],
    "ppc": ["点击付费", "PPC", "pay-per-click", "trả tiền mỗi click"],
    "proxy": ["代理", "proxy", "proxies"],
    "python": ["Python", "python编程", "py"],
    "react": ["React", "ReactJS", "react.js"],
    "redis": ["Redis", "缓存"],
    "referral": ["推荐", "推荐码", "referral", "giới thiệu", "mã giới thiệu"],
    "research": ["研究", "Research"],
    "rl": ["强化学习", "reinforcement-learning"],
    "rn": ["React Native", "react-native"],
    "robotics": [],
    "ruby": ["Ruby", "ruby语言"],
    "rust": ["Rust", "rust语言", "rust编程"],
    "saas": ["软件即服务", "SaaS", "saas", "phần mềm dịch vụ"],
    "science": ["科学", "Science"],
    "scraping": ["爬虫", "数据抓取", "web-scraping", "scraping", "cào dữ liệu"],
    "security": ["安全", "网络安全", "Security"],
    "seo": ["搜索引擎优化", "SEO", "tối ưu công cụ tìm kiếm", "tối ưu SEO"],
    "serverless": ["无服务器", "Serverless"],
    "sglang": ["SGLang"],
    "sidehustle": ["副业", "side-hustle", "side hustle", "nghề tay trái", "việc tay trái"],
    "smart-contract": ["智能合约", "smart-contracts", "Smart Contracts"],
    "social-media": ["社交媒体", "social-media", "social media", "mạng xã hội"],
    "spring": ["Spring", "Spring Boot"],
    "stocks": ["股票", "stocks", "stock", "cổ phiếu", "chứng khoán"],
    "svelte": ["Svelte"],
    "swift": ["Swift"],
    "systems": ["系统"],
    "terminal": ["终端", "Terminal"],
    "terraform": ["Terraform", "IaC"],
    "testing": ["测试", "Testing"],
    "theory": ["理论", "Theory"],
    "tiktok": ["抖音国际版", "TikTok", "tiktok"],
    "tools": ["工具", "Tools"],
    "trading": ["交易", "trading", "giao dịch"],
    "traffic": ["流量", "traffic", "lưu lượng", "lưu lượng truy cập"],
    "trending": ["趋势", "Trending"],
    "typescript": ["TypeScript", "TS", "ts"],
    "vpn": ["虚拟专用网络", "VPN", "vpn"],
    "vue": ["Vue", "VueJS", "vue.js", "vue框架"],
    "youtube": ["油管", "YouTube", "youtube"],
    "zig": [],
}

# Reverse lookup: alias (lowercased) -> canonical tag
_REVERSE_MAP: dict[str, str] = {}
for _main, _aliases in TAG_ALIASES.items():
    _REVERSE_MAP[_main.lower()] = _main
    for _alias in _aliases:
        _REVERSE_MAP[_alias.lower()] = _main


def get_tag_aliases(tag: str) -> list[str]:
    """Return all aliases for a canonical tag (empty list if unknown)."""
    return TAG_ALIASES.get(tag.lower(), [])


def resolve_tag_alias(input_str: str) -> str:
    """Resolve a tag or alias to its canonical form (lowercased)."""
    normalized = input_str.lower().strip()
    resolved = _REVERSE_MAP.get(normalized)
    return resolved if resolved else normalized
